### PR TITLE
Support nova 4

### PR DESCRIPTION
**Pull request by anditsung**
support laravel nova 4 (4.60)

Screen Shot 2022-05-21 at 12 06 44

====

have issue when user change the locale from the user resource will not update the current locale on component

==== 

```
protected $middlewareGroups = [
        'web' => [
            \Eolica\NovaLocaleSwitcher\Http\Middleware\LocaleSwitcher::class,
        ],
    ];
```

add this middleware instead of using nova serving to change locale.
if using nova serving some language is not translated ( update & continue editing )
Screen_Shot_2022-05-21_at_11 48 26

### CODE REVIEW

**Comment by NoahNxT** [comment]
Looking forward to see this merged!

**Comment by NoahNxT** [comment]
Fully tested locally and works like a charm 😎

**Comment by NoahNxT** [comment]
But don't forget to update the documentation and add the part that you'll have to add the column "locale" to your user model migration.

**Comment by NoahNxT** [comment]
@anditsung

**Review by NoahNxT — APPROVED** [review]

**Review by AbdelAziz-hassan — APPROVED** [review]

**Review by nurmuhammet-ali — APPROVED** [review]

**Pull request merged**
